# admin/config.yml

backend:
  name: github
  repo: Thinhskyduck/VietSangGroup
  branch: blog-dev

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Tin Tức & Bài Viết"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Tác giả", name: "author", widget: "string", default: "Việt Sáng Home" }
      - { label: "Ảnh đại diện", name: "image", widget: "image", required: false }
      - { label: "Tóm tắt ngắn", name: "summary", widget: "text", required: false }
      # SỬ DỤNG WIDGET MARKDOWN CÓ SẴN VÀ BẬT WYSIWYG
      - label: "Nội dung chi tiết"
        name: "body"
        widget: "markdown"
        editor_components: [] # Dòng này để tắt các tính năng nâng cao không cần thiết
        buttons: # Liệt kê các nút bạn muốn có trên thanh công cụ
          - bold
          - italic
          - link
          - quote
          - bulleted-list
          - numbered-list